services:
  relayer:
    # image: ghcr.io/vechain/vebetterdao-relayer-node:latest # uncomment to pull the image from GitHub Container Registry
    build: .
    restart: unless-stopped
    secrets:
      - mnemonic
    environment:
      - RELAYER_NETWORK=mainnet

secrets:
  mnemonic:
    file: ./secrets/mnemonic.txt
